### ISSUE TITLE
Mismatched IdToken expiration date with the reported IdTokenExpiresAt property

### ISSUE THREAD

**Issue by cmlindstrom** [auth0-community/auth0-WinFormsWPF-oidc-samples#4]
When using the LoginAsync call, an Auth0User is successfully returned, along with a valid IdToken, however the IdTokenExpiresAt doesn't match the IdToken's embedded expiration date and time.

Call
           Dim myUser As Global.Auth0.Windows.Auth0User = Await client.LoginAsync(ParentForm,, , myParams, True, strDevice)

Partial Results (myUser serialized to Json)
    "Auth0AccessToken": "Fam1mw..",
    "IdToken": "eyJ0eXAiOiJKV...",
    "IdTokenExpiresAt": "9999-12-31T23:59:59.9999999",
    "Profile": {

It looks like a default value versus a populated value.

Is this an issue you see?

thx
Chris

**Comment by jerriep** [comment]
@cmlindstrom It appears you are using the old libraries. The new OidcClient libraries does not have an `Auth0User` class. Can you please double-check for me what NuGet package you are using?

You can find the correct WPF / Windows Forms instructions over here:
https://auth0.com/docs/quickstart/native/wpf-winforms

**Comment by cmlindstrom** [comment]
Thanks I’m using the latest stable version of the library 0.9.0 (Auth0.WinformsOrWPF) – Auth0.Windows.dll v0.7.5.0 is referenced.

[cid:image002.png@01D3A0D3.93C485B0]

What am I missing?

Thx
Chris

**Comment by jerriep** [comment]
As I said, you are using an old library. Please follow the steps in the Quickstart I linked before which will show you how to use the correct library
