### ISSUE TITLE
Need to store extra user data, like expiry date, type of package

### ISSUE THREAD

**Issue by jjTudu** [auth0-community/auth0-WinFormsWPF-oidc-samples#5]
1. How to store extra user data like expiry date? and how to check it when user login is in process(In guess in Rules)?

2. And will it be possible to restrict Multiple login from same credentials? means if user is logged in Terminal A, and if again he tries to log in Terminal B, he should be logged in, but Terminal A should be logout automatically.

3. Activation of user should be done after Admin allows, not right after SignUp
i am trying in WPF

**Comment by jerriep** [comment]
@jjTudu Please contact [Auth0 Support](https://support.auth0.com/) regarding these issues as they will be able to better assist you. 

I am a freelancer working specifically with the .NET libraries, and as such, I am not really in a position to assist you. Also, the Auth0 support team do not monitor these GitHub issues, so they will not give you an answer here.
